[project]
name = "my-ai-journey"
version = "0.1.0"
description = "My journey with AI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.9.5",
]
